name: Test
on: push  # yamllint disable-line rule:truthy

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: cd build && cmake .. && make && cd ..

      - name: Test project
        run: ./test/run.sh
